language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-plum' ]; then cd .. && eval "mv $currentfolder generator-plum" && cd generator-plum; fi
